services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=${DATABASE_DB}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
    ports:
      - ${DATABASE_PORT}
